Sumekami = { Sexpr* }

Sexpr = { List | Literal | Symbol }

List = { "(" ~ Sexpr* ~ ")" }

Literal = { String | Number }

String =  _{ PUSH(DoubleQuote) ~ StringValue ~ POP }
StringValue = { (!PEEK ~ ANY)* }
DoubleQuote = _{ "\"" }

Symbol = @{ ASCII_ALPHANUMERIC+ }
Number = @{ ASCII_DIGIT+ }

COMMENT = _{ COMMENT_MARKER ~ COMMENT_CONTENT ~ NEWLINE}
COMMENT_CONTENT = { (!NEWLINE ~ ANY)* }
COMMENT_MARKER = { ";" }
WHITESPACE = _{ " " | "\t" | NEWLINE }